before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: wPcriBBG9K0+edIIeSUfY1TI1OTjUDHW/0m7PUbmEsfT28srbwdFOuQcgX8/yVajk9OZTbx0nxCTn4KLSGxCQ+NVpFX0Xjqmk4v3d9/odPxu87iKFWz4TobxBTAq97PdZ1mItjJEGjVyEWAupA/gXRqgdg3IxJW8rnLo+TlJ/NIMFAHhHfJtU7DwCDIHroeUtZUkNHOjofLidcnS843ZNdQg1ktxrSso+xE3MPsoASnxFRy8v3MOtjU6SYNVnjVw4N91JYNKyp26SzgNVJrV3AdhEUaFo+n8R4auVPn7wvhhZAXR6VCUh8YoyBZ51st2rdUBVFgnvAdCR3TrPDJr1NvDlx79mFo+zDJB0fqbiUs2Fgf62wjq7kEPlZOX5/onJyIqcJBb9SHt2cGTjIEcqrb3WvZWWOxcNF6aL3FEMDNJ4cySFszaZj2XCBsOktnNc7ggXdEhVyPT+JEzXPt/wux8hrAy60b8R6lzhYWrlJe6Raq3U7UMfm1+qvqtGL7OAGAn7Vd5kvo9Fc9GAFpYVGhWDma+lJQxcjZJAYU9W7XuQlrIvhEi9UgXYc+1vknBnrPQPDMyHYLGBtSsys7meWdjNQ9AFL5oP8cY8t/gdy6NKS7ohP0F84ydw7mbe2Zth9lTYCb1ib9ovcpA8tFa81/RO75XSl5BT65nOKFWLr4= # CRYPTO_AES_KEY
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
